version: "3.3"

services:
  package-service:
    build: ./package-service
    ports:
      - 6000:7000
      - 6001:7001
      - 6002:7002
  dependency-service:
    build: ./dependency-service
    ports:
      - 8000:7000
      - 8001:7001
      - 8002:7002
  postgres-ps:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
