// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/dependency-service.proto

package dependency_service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on GetPackageDepsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetPackageDepsRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// GetPackageDepsRequestValidationError is the validation error returned by
// GetPackageDepsRequest.Validate if the designated constraints aren't met.
type GetPackageDepsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPackageDepsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPackageDepsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPackageDepsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPackageDepsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPackageDepsRequestValidationError) ErrorName() string {
	return "GetPackageDepsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPackageDepsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPackageDepsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPackageDepsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPackageDepsRequestValidationError{}

// Validate checks the field values on GetPackageDepsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetPackageDepsResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// GetPackageDepsResponseValidationError is the validation error returned by
// GetPackageDepsResponse.Validate if the designated constraints aren't met.
type GetPackageDepsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPackageDepsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPackageDepsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPackageDepsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPackageDepsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPackageDepsResponseValidationError) ErrorName() string {
	return "GetPackageDepsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPackageDepsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPackageDepsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPackageDepsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPackageDepsResponseValidationError{}
